<?php
/**
 * LCS Amanda
 * 
 * Copyright (c) 2025 - Loaded Channel Solutions
 * Licensed under the MIT License. See LICENSE file for details.
 * 
 * Please do not edit this file.
 * 
 * @package LCS Amanda
 * @version 1.0.0
 * @license MIT
 * @author LOADED CHANNEL SOLUTIONS LTD, Chinonso Justice
 * @link https://lcs.ng/amanda
 */

// Include $amanda_request instance
$amandaRequestInstance = __DIR__ . "/../amanda/amanda_rc.php";
require_once ($amandaRequestInstance);

// Secure the AJAX request by validating the origin and request method
$amanda_request->secure_ajax_request(false);

$ajaxRequestData = $amanda_request->get_request_data();

if (!isset($ajaxRequestData['action']) || !is_string($ajaxRequestData['action'])) {
    $amanda_request->send_json_error('Invalid action!');
}

$ajaxRequestAction = (string) 'amanda_ajax_' . $ajaxRequestData['action'];

// Define the path to Amanda functions file
$amandaFunctions = __DIR__ . "/../amanda/amanda_functions.php";

// Include Amanda functions to provide additional functionalities
require_once ($amandaFunctions);

if (!amanda_has_action($ajaxRequestAction)) {
    $amanda_request->send_json_error("Action does not exist! $ajaxRequestAction");
}

amanda_do_action($ajaxRequestAction);