<?php
/**
 * LCS Amanda
 * 
 * Copyright (c) 2025 - Loaded Channel Solutions
 * Licensed under the MIT License. See LICENSE file for details.
 * 
 * Please do not edit this file.
 * 
 * @package LCS Amanda
 * @version 1.0.0
 * @license MIT
 * @author LOADED CHANNEL SOLUTIONS LTD, Chinonso Justice
 * @link https://lcs.ng/amanda
 */


/**
 * Include LCS External class autoloader
 */
require_once ( __DIR__ . '/../lcs_ext_library/vendor/autoload.php' );

/**
 * Include Dotenv
 */
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

/**
 * Suppress Deprecation warnings
 */
error_reporting(E_ALL & ~E_DEPRECATED);

/**
 * Amanda host
 */
define('AMANDA_HOST', parse_url("https://" . $_SERVER['HTTP_HOST'], PHP_URL_HOST));

/**
 * Amanda url
 */
define('AMANDA_URL', (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://" . $_SERVER['HTTP_HOST']);

/**
 * Amanda public directory
 */
define('AMANDA_PUBLIC_DIR', '/');

/**
 * Amanda AJAX endpoint
 */
define('AMANDA_AJAX_ENDPOINT', AMANDA_PUBLIC_DIR . 'amanda_ajax.php');

/**
 * Amanda AJAX object meta tag
 */
define('AMANDA_AJAX_OBJECT_META', '<meta name=\'lcs_ajax_object\' content=\'{"ajaxurl":"' . AMANDA_AJAX_ENDPOINT . '"}\'>');

/**
 * Amanda assets directory
 */
define('AMANDA_ASSETS_DIR', AMANDA_PUBLIC_DIR . 'amanda_assets');

/**
 * Amanda Official Assets directory
 */
define('AMANDA_OA_DIR', AMANDA_ASSETS_DIR . '/oa');

/**
 * Amanda directory path
 */
define('AMANDA_DIR', __DIR__);

/**
 * Amanda template directory path
 */
define('AMANDA_TEMPLATE_DIR', AMANDA_DIR . '/amanda_templates');

/**
 * Amanda mailing credentials
 */
define('AMANDA_MAILING_HOST', $_ENV['AMANDA_MAILING_HOST']);
define('AMANDA_MAILING_USERNAME', $_ENV['AMANDA_MAILING_USERNAME']);
define('AMANDA_MAILING_PASSWORD', $_ENV['AMANDA_MAILING_PASSWORD']);

/**
 * Define global variables for instances of LCS External classes
 */
use LCSNG_EXT\Creds\LCS_Creds;
use LCSNG_EXT\FileManagement\LCS_FileManager;
use LCSNG_EXT\Mailing\LCS_Mail;
use LCSNG_EXT\Hooks\LCS_Hook;
use LCSNG_EXT\Database\LCS_DBManager;
use LCSNG_EXT\Database\LCS_DBTable;

/**
 * Define database connection variables
 */
$dbCreds = $_ENV['AMANDA_DB_CREDS'] ?? '';

// Include request config file
require_once ('amanda_rc.php');

// Initialize LCS Creds global instance
global $amanda_creds;
$amanda_creds = new LCS_Creds();

// Initialize file manager global instance
global $amanda_fm;
$amanda_fm = new LCS_FileManager();

// Initialize mailer global instance
global $amanda_mailer;
$amanda_mailer = new LCS_Mail(AMANDA_MAILING_HOST, AMANDA_MAILING_USERNAME, AMANDA_MAILING_PASSWORD);

// Initialize the LCS Hook
global $amanda_hooks;
$amanda_hooks = new LCS_Hook();

// Initialize the database manager
global $amanda_db;
$amanda_db = new LCS_DBManager($dbCreds, ['FETCH_MODE' => 'ARRAY'], 'MySQLi');

// Initialize the database table manager
global $amanda_db_table;
$amanda_db_table = new LCS_DBTable($amanda_db->credentials, $amanda_db->options, $amanda_db->sql_manager);