<?php
/**
 * LCS Amanda
 * 
 * Copyright (c) 2025 - Loaded Channel Solutions
 * Licensed under the MIT License. See LICENSE file for details.
 * 
 * Please do not edit this file.
 * 
 * @package LCS Amanda
 * @version 1.0.0
 * @license MIT
 * @author LOADED CHANNEL SOLUTIONS LTD, Chinonso Justice
 * @link https://lcs.ng/amanda
 */


/**
 * Include LCS External class autoloader
 */
require_once ( __DIR__ . '/../vendor/autoload.php' );

// Initialize the request controller
use LCSNG_EXT\Requests\LCS_Request;
global $amanda_request;
$amanda_request = new LCS_Request(true);

// Initialize the routing controller
use LCSNG_EXT\Requests\LCS_RoutingController;
global $amanda_router;
$amanda_router = new LCS_RoutingController();